apiVersion: v1
kind: Service
metadata:
  name: notification-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: LoadBalancer
